Resources
| where type =~ "microsoft.managedidentity/userassignedidentities/federatedidentitycredentials"
| extend parentUami = tostring(split(id, "/federatedIdentityCredentials/")[0])
| project id,
          name      = tostring(properties.name),
          issuer    = tostring(properties.issuer),
          subject   = tostring(properties.subject),
          audiences = properties.audiences,
          parentUami
